spring:
  application:
    name: discodeit
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL 줄바꿈 및 들여쓰기
        use_sql_comments: true # 쿼리 앞에 주석 출력
        highlight_sql: false # 컬러로 SQL 표현
        generate_statistics: false #실행 통계 출력
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

info:
  app:
    name: ${spring.application.name}
    description: 디스코드 클론 프로젝트
    version: 1.7.0
    author: junwo
    java-version: ${java.version}
    spring-boot-version: 3.4.0
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers
  info:
    env:
      enabled: true


server:
  port: 8081