spring:
  profiles:
    active: prod
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

logging:
  level:
    org.hibernate.SQL: info

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage
