spring:
  application:
    name: discodeit
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  boot:
    admin:
      client:
        instance:
          name: discodeit

logging:
  level:
    org.hibernate.SQL: info

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage