spring:
  application:
    name: discodeit
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

logging:
  level:
    org.hibernate.SQL: info

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage