package com.sprint.mission.discodeit;

import com.sprint.mission.discodeit.entity.Channel;
import com.sprint.mission.discodeit.entity.Message;
import com.sprint.mission.discodeit.entity.User;
import com.sprint.mission.discodeit.log.MyLog;
import com.sprint.mission.discodeit.service.ChannelService;
import com.sprint.mission.discodeit.service.MessageService;
import com.sprint.mission.discodeit.service.UserService;
import com.sprint.mission.discodeit.service.jcf.JCFChannelService;
import com.sprint.mission.discodeit.service.jcf.JCFMessageService;
import com.sprint.mission.discodeit.service.jcf.JCFUserSerivce;

import java.util.List;

public class JavaApplication {
    private static UserService userService = new JCFUserSerivce();
    private static MessageService messageService = new JCFMessageService(userService);
    private static ChannelService channelService = new JCFChannelService(userService);

    public static void main(String[] args) {
        System.out.println("<회원 생성하기>");
        MyLog<User> user1 = userService.createUser("김민준", "010-1111-1111", "1234");
        MyLog<User> user1_1 = userService.createUser("홍지훈", "010-1111-1111", "1234");
        MyLog<User> user2 = userService.createUser("이서윤", "010-2222-1111", "1234");
        MyLog<User> user3 = userService.createUser("박지훈", "010-3333-1111", "1234");
        MyLog<User> user4 = userService.createUser("최지아", "010-4444-1111", "1234");
        MyLog<User> user5 = userService.createUser("정다은", "010-5555-1111", "1234");
        System.out.println(user1.getData() + user1.getMessage());
        System.out.print("동일한 전화번호로 회원가입을 진행한 다른 사람 : ");
        System.out.println(user1_1.getMessage());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<회원 전체 조회하기>");
        List<User> users = userService.getAllUser();
        System.out.println(users);
        System.out.println();
        System.out.println("<단일 회원 조회하기>");
        MyLog<User> findUser1 = userService.getUserById("010-1111-1111");
        System.out.println(findUser1.getData() + " " +findUser1.getMessage());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<회원 비밀번호 업데이트 하기>");
        MyLog<User> updateUser1 = userService.updateUserPassword("010-1111-1111", "0912");
        System.out.println(updateUser1.getData() + " " + updateUser1.getMessage());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<회원 정보 삭제하기>");
        MyLog<User> deleteUser1 = userService.deleteUser(user1.getData());
        System.out.println(deleteUser1.getData() + deleteUser1.getMessage());
        System.out.println(userService.getAllUser());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<메시지 생성하기>");
        MyLog<Message> message2To3 = messageService.createMessage("안녕하세요 지훈님 저는 이서윤이라고 합니다.", user2.getData(), user3.getData());
        System.out.println(message2To3.getData());
        MyLog<Message> message3To2 = messageService.createMessage("네 만나서 반갑습니다!", user3.getData(), user2.getData());
        System.out.println(message3To2.getData());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<전체 메시지 조회하기>");
        List<Message> allMessages = messageService.getAllMessages();
        System.out.println(allMessages);
        System.out.println("<단일 메시지 조회하기>");
        MyLog<List<Message>> getMessage = messageService.getMessageByUser(user2.getData(), user3.getData());
        System.out.println(getMessage.getData());
        MyLog<List<Message>> getMessageByDiff = messageService.getMessageByUser(user2.getData(), user4.getData());
        System.out.println("user2 -> user4 메시지 조회: " + getMessageByDiff.getMessage());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<메시지 내용 수정하기>");
        messageService.updateMessageId(message2To3.getData().getId(), "메시지 내용 업데이트");
        System.out.println(message2To3.getData());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<메시지 삭제하기>");
        MyLog<Message> deleteMessage = messageService.deleteMessage(message2To3.getData());
        System.out.println("user2 -> user3: " + deleteMessage.getMessage());
        System.out.println("전체 메시지 조회하기: " + messageService.getAllMessages());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<채널 생성하기>");
        MyLog<Channel> channel1 = channelService.createChannel(userService.getAllUser(), "코드잇 디스코드", user2.getData());
        MyLog<Channel> channel2 = channelService.createChannel(userService.getAllUser(), "코테 준비", user3.getData());
        System.out.println(channel1.getData());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<채널 단일 조회하기>");
        MyLog<Channel> findChannel1 = channelService.getChannelByName("코드잇 디스코드");
        System.out.println("코드잇 디스코드 채널 찾기 : " + findChannel1.getData());
        System.out.println("<전체 채널 조회하기>");
        List<Channel> allChannel = channelService.getAllChannel();
        System.out.println(allChannel);
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<채널에 새로운 멤버 추가하기>");
        User newUser = new User("홍길동", "010-1234-4321", "1234");
        MyLog<Channel> updateChannel2 = channelService.updateChannel("코테 준비", newUser);
        System.out.println("코테 준비 채널에 신규 회원 추가 : " + updateChannel2.getData());
        System.out.println();
        System.out.println("===============================================================================");
        System.out.println();
        System.out.println("<채널 삭제하기>");
        MyLog<Channel> deleteChannel1 = channelService.deleteChannel("코테 준비");
        System.out.println("코테 준비 채널 삭제하기: " + deleteChannel1.getMessage());
        System.out.println(channelService.getAllChannel());
    }
}
