name: Build and Push to Public ECR

on:
  push:
    branches: [release]

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1  # ✅ Public ECR은 무조건 이 리전!

      - name: Login to Amazon Public ECR
        run: aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and push Docker image to Public ECR
        env:
          ECR_REGISTRY: public.ecr.aws/r0n8y0y0/discodeit
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-8)
          docker build -t $ECR_REGISTRY:latest -t $ECR_REGISTRY:$COMMIT_HASH .
          docker push $ECR_REGISTRY:latest
          docker push $ECR_REGISTRY:$COMMIT_HASH
