name: Run Tests and Upload Coverage

on:
  pull_request:
    branches:
      - main
      - part3-김준우-dev

jobs:
  test:
    name: Run tests & upload coverage
    runs-on: ubuntu-latest

    env:
      RUN_S3_TEST: "true"
      AWS_S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_S3_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_S3_REGION: ${{ vars.AWS_REGION }}
      AWS_S3_BUCKET: ${{ vars.AWS_BUCKET }}
      AWS_S3_PRESIGNED_URL_EXPIRATION: "600"

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5  # ✅ 들여쓰기 수정
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: normaldeve/1-sprint-mission